version: '3'
services:
  db:
    image: mysql:latest
    container_name: dba
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 111
      MYSQL_DATABASE: rotr
    ports:
      - "2306:3306"